### PR TITLE
adding rtcp processing example

### PR DESCRIPTION
**Pull request by themusicman**
Wanted to contribute an example like the one in the Pion project here: https://github.com/pion/webrtc/tree/master/examples/rtcp-processing

### CODE REVIEW

**Comment by mickel8** [comment]
Hi @themusicman, thanks for the contribution!

A couple of notes:
* current example is almost the same as the `echo` example so we add a lot of code that we need to maintain and update as API changes
* handling RTCP in ex_webrtc is a little easier as we get those packets automatically. I can see why Pion has a separate example for this as they need to call ReadRTCP in a loop ([link](https://github.com/pion/webrtc/blob/master/examples/rtcp-processing/main.go#L39-L52))

I would favor adding a clause for RTCP in our `echo` example that just ignores those packets. We can add a short comment too. Something like this:

```elixir
  defp handle_webrtc_msg({:rtcp, _packets}, state) do
    # do something with RTCP packets
    {:ok, state}
  end
```

This way:
* we show how to receive RTCP packets
* we don't add too much extra code that needs to be maintained
* we don't send messages to the FE or log them in the console so the output is clean

**Comment by themusicman** [comment]
@mickel8 Fair points. I updated the PR.

**Comment by mickel8** [comment]
Thanks for the PR @themusicman! i have deleted the comment as we are going to talk about RTCP in our guides section (in hex docs) at some point. 

> Is there anything that you want help with in regards to the project? Maybe RTCP Sender and Receiver Reports?

That's something @LVala is already working on!
When it comes to the roadmap itself, I am working on ICE features (mDNS and TURN servers support) . 

Other things I have in my mind but are not planned for 0.2 (i.e. neither @LVala  nor me are going to work on them)
* support for AV1 codec, see #35 
* datachannels
* ex_webrtc_dashboard - more metrics, performance optimizations 
* jitter buffer 


and many more, I will update the list later this evening :wink:

**Comment by themusicman** [comment]
@mickel8 I was thinking about suggesting datachannels too. I will look into that some and come up with a plan for implementation and present it to you. What do you think about that?

**Comment by mickel8** [comment]
@themusicman Sounds great!

**Comment by mickel8** [comment]
@themusicman I've created a new section in our Roadmap where I put things that can be addressed: https://github.com/elixir-webrtc/ex_webrtc/issues/28

**Pull request merged**
