### PR TITLE
Add behaviour and dynamic dispatch for (de)payloaders

### LINKED ISSUE #143: Create a common behaviour for payloaders and depayloaders

### PR DESCRIPTION
**Pull request by sgfn**
Closes #143

### CODE REVIEW

**Review by LVala — COMMENTED** [review]
I'm a bit unsure about adding specs to callback implementation. I believe that `ex_doc` will generate the spec anyway (based on the callback) and making the callback and implementation spec different is a big yucky, but on the other hand, we know that e.g. `Opus.depayload` will never return `{nil, depyayloader}`. I'm a bit torn when it comes to this.

**Comment by LVala** [comment]
Removing the `@doc` will automatically add a doc with "Callback implementation for <link to docs for the callback>". Indeed, not `@spec` in such a case.

Not sure which one is better, but having explicit spec seems more useful.

**Comment by mickel8** [comment]
I think that at the end of the day, we don't want to document functions from Opus/VP8 payloaders/depaylaoders. Instead, the whole documentation should be in the behaviour module or in the module that is responsible for dispatching or in both. 

E.g.

```elixir
d = ExWebRTC.RTP.Depayloader.new(ExWebRTC.RTP.Depayloader.VP8, some_options)
{frame, d} = ExWebRTC.RTP.Depayloader.depayload(d, packet)
```

In such case, we only need to document ExWebRTC.RTP.Depayloader.VP8 module.  Its functions shouldn't appear in docs. But this is the final outcome.

**Review by mickel8 — APPROVED** [review]

**Comment by sgfn** [comment]
@mickel8 Could you please reiterate on how exactly do you suggest the docs should look like? Specifically, which parts should I get rid of?

**Comment by mickel8** [comment]
@sgfn please take a look at #154

**Pull request merged**
